# Generated by Django 5.2.1 on 2025-06-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contributionplan",
            name="daily_amount",
            field=models.PositiveIntegerField(
                choices=[
                    (500, "₦500 / day"),
                    (1000, "₦1,000 / day"),
                    (5000, "₦5,000 / day"),
                    (10000, "₦10,000 / day"),
                    (20000, "₦20,000 / day"),
                    (50000, "₦50,000 / day"),
                ]
            ),
        ),
    ]
