# Generated by Django 5.1.1 on 2025-06-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_depositrequest_withdrawrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="profile_pics/default.jpg", upload_to="profile_pics/"
            ),
        ),
        migrations.AlterField(
            model_name="contributionplan",
            name="daily_amount",
            field=models.PositiveIntegerField(
                choices=[
                    (500, "₦500 / day"),
                    (1000, "₦1,000 / day"),
                    (2000, "₦2,000 / day"),
                    (3000, "₦3,000 / day"),
                    (4000, "₦4,000 / day"),
                    (5000, "₦5,000 / day"),
                    (10000, "₦10,000 / day"),
                    (15000, "₦15,000 / day"),
                    (20000, "₦20,000 / day"),
                    (50000, "₦50,000 / day"),
                ]
            ),
        ),
    ]
