# Generated by Django 5.1.1 on 2025-06-03 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_profile_image_alter_contributionplan_daily_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="image",
        ),
    ]
