# Generated by Django 5.1.1 on 2025-06-03 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_remove_profile_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="photo",
            new_name="image",
        ),
    ]
