# Generated by Django 5.1.1 on 2025-06-03 11:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_rename_photo_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                default="profile_pics/default.jpg",
                max_length=255,
                null=True,
                verbose_name="image",
            ),
        ),
    ]
