# Generated by Django 5.1.1 on 2025-06-04 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="withdrawrequest",
            name="account_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="withdrawrequest",
            name="account_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="withdrawrequest",
            name="bank_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
